models: 
  embedding_model: "qwen3-embedding:4b"       
  embed_batch_size: 32
  qa_dataset_generation_model: "gemma4:26b" # LLM used in QA dataset generation scripts

  # options to ensure reproducible outputs on every call
  seed: 7
  temperature: 0.0

neo4j: 
  uri: "bolt://localhost:17687"
  user: "neo4j"
  password: "X"

relational_qa_dataset_generation:
  queries_per_template: 1
  prompt: |-
    You are an intelligent assistant that generates queries about Amazon items.
    I will provide you with a golden path from an Amazon product recommendation knowledge graph which leads to {num_answers} product(s).
    Your task is to create a natural-sounding customer query that leads to the target product(s) as the answer.
    Make sure to not confuse the product relations "also_view" and "also_buy" in the query.
    Do not shorten product names in a way that may confuse them with similar products.

    Path:
    {path}

    Query: 

textual_qa_dataset_generation:
  num_queries: 5
  query_gen_prompt: |-
    You are an intelligent assistant that generates queries about Amazon items.
    I will provide you with a textual document associated with a product entity in a Amazon product recommendation knowledge graph.
    Your task is to create a natural-sounding customer query that leads to this entity as the answer.
    Try to use many different aspects of the document in your query, such as features, reviews or specifications.
    Do not use the product name directly in your query.

    Document:
    {doc}

    Query: 
  similar_nodes_cypher: |-
    MATCH (p1:product {{id: '{id}'}})
    MATCH (p2:product)
      SEARCH p2 IN (
        VECTOR INDEX product_index
        FOR p1.embedding
        LIMIT 5
      )
    WHERE p1.id <> p2.id
    RETURN p2.document AS document
  ambiguity_check_prompt: |-
    You are an intelligent assistant that checks if a query is ambiguous.
    I will provide you with a list of documents, each describing a different product.
    Document #0 is the document the query was generated with.
    The other documents are semantically similar documents.

    Please decide:
    - "KEEP" if the query is specific enough to only lead to document #0 as the answer.
    - "DISCARD" if the query could be understood to lead to one of the other documents as well. 

    Query: {query}

    Documents:
    {documents}

graph_entity_count: 1035542